x-variables: &defaults
  BACKEND_CONTAINER_NAME: ${BACKEND_CONTAINER_NAME:-laravel-backend}
  FRONTEND_CONTAINER_NAME: ${FRONTEND_CONTAINER_NAME:-vue-frontend}
  DB_CONTAINER_NAME: ${DB_CONTAINER_NAME:-postgres-db}
  ADMINER_CONTAINER_NAME: ${ADMINER_CONTAINER_NAME:-adminer}

services:
  # Laravel backend
  backend:
    build:
      context: .
      dockerfile: .docker/backend/Dockerfile
    container_name: ${BACKEND_CONTAINER_NAME:-laravel-backend}
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    ports:
      - "${BACKEND_PORT:-8000}:80"
    environment:
      APP_ENV: ${APP_ENV:-local}
      APP_DEBUG: ${APP_DEBUG:-true}
      APP_KEY: ${APP_KEY:-base64:random-key-placeholder}
      DB_CONNECTION: ${DB_CONNECTION:-pgsql}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      DB_DATABASE: ${DB_DATABASE:-laravel}
      DB_USERNAME: ${DB_USERNAME:-laravel}
      DB_PASSWORD: ${DB_PASSWORD:-secret}
    depends_on:
      - db
    networks:
      - app-network

  # Vue frontend
  frontend:
    build:
      context: .
      dockerfile: .docker/frontend/Dockerfile
    container_name: ${FRONTEND_CONTAINER_NAME:-vue-frontend}
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    command: >
      sh -c "
      yarn install &&
      yarn dev --host
      "
    networks:
      - app-network

  # PostgreSQL Database
  db:
    image: postgres:latest
    container_name: ${DB_CONTAINER_NAME:-postgres-db}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-laravel}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-laravel}
    networks:
      - app-network

  # Adminer for database management
  adminer:
    image: adminer:latest
    container_name: ${ADMINER_CONTAINER_NAME:-adminer}
    ports:
      - "${ADMINER_PORT:-8080}:8080"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
